### ISSUE TITLE
Column Show/Hide is possible

### ISSUE THREAD

**Issue by HariKiran9** [Swimlane/angular-data-table#142]
Possibility of Column Show/Hide

**Comment by amcdnl** [comment]
see: https://github.com/Swimlane/angular-data-table/blob/master/demos/columnadd.html

**Comment by kuzman** [comment]
I must say it is a bit confusing this line in the example: 
`<dtm available="all" current="cur" class="my-menu"></dtm>`

what is the 'dtm' directive's purpose?
does this mean we need to keep two definitions of the columns?

maybe it is possible, but I couldn't find it, to have a "show" or "hide" option and put a $watcher on it? 
know we add just another watcher and thus degrading the performances, but I think that this would be a very important feature.
or to go even further, let say to add more freedom to the developer, maybe to expose some API to the developer?

**Comment by amcdnl** [comment]
the dtm is a example directive of how to implement a show/hide menu with the table.

Adding/removing columns is implementation specific, we decoupled this on purpose since the ui, implementation, etc vary based on your scenario.

There is no need for a watcher, you just update your columns and the new columns. Its knows how to react based on your new changes. see: https://github.com/Swimlane/angular-data-table/blob/master/src/components/DataTableController.js#L26

Is there a specific problem your having you can accomplish with this interface contract?

**Comment by VaradaJnana** [comment]
Hi, I am not using ES6 and i have installed data-table with bower. i want to Show/Hide columns in my project but if i inject dt.menu . angular is not detecting the module. how can i use this in my gulp based project. !?
