### ISSUE TITLE
Why create a new ng scope for cell renderers?

### ISSUE THREAD

**Issue by ghost** [Swimlane/angular-data-table#228]
Hi, I'm a developer in the team who brought you PR #219.

When we declare a cellRenderer, you create a new scope for the cell and watch modification on the row's data in order to update the view.
See [CellDirective.js](https://github.com/swimlane/angular-data-table/blob/master/src/components/body/CellDirective.js).

The row already has a scope due to the RowDirective.
Wouldn't it be more efficient to use that scope instead of creating a new one yourself?
The goal is not to have a new scope per cell, which is extremely inefficient in our case.

The reason I ask this question is that we have really poor performance on a 50 row grid with 20 columns, each having a custom cellRenderer function.
We must use this because with want two lines of data inside one cell.

Thanks

**Comment by nokkypx** [comment]
+1 on performance, we have 1000 rows and 20 columns and each cell has a renderer function.
if i remove the cells with the renderer functions from the view i get great performance.

**Comment by amcdnl** [comment]
20 Columns Performance is not related to scope creation ( well maybe in a inadvertent way? ). That's just the pure amount of DOM on the screen since Horz is not virtualized.

While I agree that creating new scope like that is not ideal, it only happens when you use templates/expressive-ness in your columns. See: https://github.com/swimlane/angular-data-table/blob/master/src/components/body/CellDirective.js#L43

The reason it does this is for your custom components/directives that are used in your templates. In Angular2 this is not nesc anymore but sadly I'm not sure another way around this for Angular1.
