### ISSUE TITLE
Virtual pagination links don't work in demos

### ISSUE THREAD

**Issue by brianfeister** [Swimlane/angular-data-table#30]
When I clone the project and run it locally, the `demos/paging.html` has links in the bottom-right and they update as I scroll, but clicking the links doesn't change / jump the scroll position.  Is this by design?  The same is true of the codepen demo, http://codepen.io/marjan-georgiev/pen/vOebGw, with the following additional problems: 
- Sometimes the data doesn't load
- Sometimes pagination doesn't trigger on scroll

My main concern is getting virtual pagination working, let me know if this is a code change.  Debugging the project locally, I see 

```
<li ng-repeat="pg in pager.pages track by $index" ng-class="{ active: pg.active }" class="ng-scope">
            <a href="" ng-click="pager.selectPage(this, pg.number)" class="ng-binding">17</a>
          </li>
```

putting a debug statement in `PagerController.js` at line 60 (`selectPage` function) it doesn't appeared to be called when I click it.

**Comment by amcdnl** [comment]
It should jump to the scroll position.  This was working, not sure what happened!

I haven't seen the issue w/ the data not loading ( likely because I mainly run local and its a race case ).  I was able to reproduce on the pen sometimes though.

I have no idea why that wouldn't fire; there is nothing indicating it shouldn't!  Thats pretty straight forward code there.

**Comment by lookfirst** [comment]
noticed this... http://take.ms/P7WNG

when i scroll down, the data shows up.

**Comment by amcdnl** [comment]
Should be resolved now.
