### ISSUE TITLE
Implemented a pagination strategy for last seen id

### ISSUE THREAD

**Issue by awartoft** [Swimlane/angular-data-table#76]
Heya,

Awesome and clean library, but i'm having some problems with larger datasets of mysql, i would like to implement a lastSeenId instead of using offset/limit, Dunno if this is possible with the existing core tho.

**Comment by amcdnl** [comment]
Can you describe the use case? 

I think I know what your are talking about, I do something similar where I have a intermediate object that represents my 'grid search report'.  I cache the offset ( unless something sorts because i do that on the server ) and then inject that range into the array that is my rows.  

Heres an example: https://gist.github.com/amcdnl/5014a8ddd65182a8a7f8

**Comment by awartoft** [comment]
Heya, Just came back to this issue, the dtable has a on-sort to which I can pass a callback, but I don't know what argument to pass to retrieve which column or direction we are trying to sort on.

**Comment by amcdnl** [comment]
see: https://github.com/Swimlane/angular-data-table/blob/master/src/components/DataTableController.js#L146
